<?php
// Inicia sessão e carrega config/sidebar
require_once __DIR__ . '/../../auth.php';
require_once __DIR__ . '/../../config/db.php';
require_once __DIR__ . '/../../sidebar.php';
?>
<!DOCTYPE html>
<html lang="pt-BR">
<head>
  <meta charset="UTF-8">
  <title>ESTOQUE BASTARDS</title>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <script src="https://cdn.tailwindcss.com"></script>
  <link rel="stylesheet" href="../../assets/css/style.css">
</head>
<body class="bg-gray-900 text-white min-h-screen flex flex-col sm:flex-row">

  <!-- Última atualização -->
  <div class="absolute top-2 right-4 text-xs text-gray-400">
    Última atualização: 05/06/2025 08:28:41
  </div>

  <!-- Conteúdo principal centralizado -->
  <main class="flex-1 p-6 bg-gray-900 overflow-auto flex flex-col items-center">

    <h1 class="text-2xl sm:text-3xl font-bold text-yellow-400 text-center mb-6">
      ESTOQUE BASTARDS
    </h1>

    <div class="mb-4 flex items-center space-x-2">
  <span class="font-semibold text-[10px] text-gray-200">Filtrar Empresa:</span>
  <div class="relative inline-block group" id="filter-container">
    <button id="btn-filter" class="bg-gray-700 hover:bg-gray-600 text-white text-[10px] px-4 py-1 rounded w-48">CERVEJARIA HRX LTDA</button>
    <div id="dropdown-menu" class="invisible group-hover:visible opacity-0 group-hover:opacity-100 absolute mt-2 w-56 bg-gray-700 rounded shadow-lg max-h-40 overflow-y-auto z-20 transition-all">
      <label class="flex items-center px-3 py-1 hover:bg-gray-600 cursor-pointer text-[10px] text-white">
        <input type="radio" name="empresa-filter" class="mr-1 accent-white" value="CERVEJARIA HRX LTDA" checked>
        CERVEJARIA HRX LTDA
      </label>
      <label class="flex items-center px-3 py-1 hover:bg-gray-600 cursor-pointer text-[10px] text-white">
        <input type="radio" name="empresa-filter" class="mr-1 accent-white" value="GO-BASTARDS BEBIDAS GO LTDA">
        GO-BASTARDS BEBIDAS GO LTDA
      </label>
      <label class="flex items-center px-3 py-1 hover:bg-gray-600 cursor-pointer text-[10px] text-white">
        <input type="radio" name="empresa-filter" class="mr-1 accent-white" value="IND. XAMA">
        IND. XAMA
      </label>
      <label class="flex items-center px-3 py-1 hover:bg-gray-600 cursor-pointer text-[10px] text-white">
        <input type="radio" name="empresa-filter" class="mr-1 accent-white" value="MG-BASTARDS BEBIDAS MG LTDA">
        MG-BASTARDS BEBIDAS MG LTDA
      </label>
      <label class="flex items-center px-3 py-1 hover:bg-gray-600 cursor-pointer text-[10px] text-white">
        <input type="radio" name="empresa-filter" class="mr-1 accent-white" value="RJ-BASTARDS BEBIDAS RJ LTDA">
        RJ-BASTARDS BEBIDAS RJ LTDA
      </label>
      <label class="flex items-center px-3 py-1 hover:bg-gray-600 cursor-pointer text-[10px] text-white">
        <input type="radio" name="empresa-filter" class="mr-1 accent-white" value="SC-BASTARDS BEBIDAS SC LTDA">
        SC-BASTARDS BEBIDAS SC LTDA
      </label>
    </div>
  </div>
</div>


    <div class="overflow-x-auto bg-gray-800 rounded-lg shadow">
      <table class="table-auto border border-white text-xs mx-auto border-collapse divide-y divide-white divide-x divide-white">
        <thead class='bg-gray-900 text-white'><tr><th class='border-r border-white px-2 py-1 whitespace-nowrap'>CERVEJA</th><th class='border-r border-white px-2 py-1 whitespace-nowrap'>BARRIL INOX 30L</th><th class='border-r border-white px-2 py-1 whitespace-nowrap'>BARRIL INOX 50L</th><th class='border-r border-white px-2 py-1 whitespace-nowrap'>BARRIL PET 30L</th><th class='border-r border-white px-2 py-1 whitespace-nowrap'>LATA 350ML</th><th class='border-r border-white px-2 py-1 whitespace-nowrap'>LATA 473ML</th></tr></thead>
        <tbody class='bg-gray-700 text-gray-100 text-xs divide-y divide-white'>
<tr data-empresa="CERVEJARIA HRX LTDA"><td class="border-r border-white px-2 py-1 whitespace-nowrap bg-gray-900 text-gray-100">ACID BLOOD</td><td class='border-r border-white px-2 py-1'><span class="text-green-500 font-bold">&#10004; 6</span></td><td class='border-r border-white px-2 py-1'><span class="text-red-500 font-bold">&#10008;</span></td><td class='border-r border-white px-2 py-1'><span class="text-green-500 font-bold">&#10004; 1</span></td><td class='border-r border-white px-2 py-1'><span class="text-red-500 font-bold">&#10008;</span></td><td class='border-r border-white px-2 py-1'><span class="text-red-500 font-bold">&#10008;</span></td></tr>
<tr data-empresa="CERVEJARIA HRX LTDA"><td class="border-r border-white px-2 py-1 whitespace-nowrap bg-gray-900 text-gray-100">CRIATURA DO PANTANO</td><td class='border-r border-white px-2 py-1'><span class="text-red-500 font-bold">&#10008;</span></td><td class='border-r border-white px-2 py-1'><span class="text-red-500 font-bold">&#10008;</span></td><td class='border-r border-white px-2 py-1'><span class="text-red-500 font-bold">&#10008;</span></td><td class='border-r border-white px-2 py-1'><span class="text-red-500 font-bold">&#10008;</span></td><td class='border-r border-white px-2 py-1'><span class="text-green-500 font-bold">&#10004; 260</span></td></tr>
<tr data-empresa="CERVEJARIA HRX LTDA"><td class="border-r border-white px-2 py-1 whitespace-nowrap bg-gray-900 text-gray-100">DOG SAVE THE BEER</td><td class='border-r border-white px-2 py-1'><span class="text-green-500 font-bold">&#10004; 8</span></td><td class='border-r border-white px-2 py-1'><span class="text-green-500 font-bold">&#10004; 1</span></td><td class='border-r border-white px-2 py-1'><span class="text-red-500 font-bold">&#10008;</span></td><td class='border-r border-white px-2 py-1'><span class="text-red-500 font-bold">&#10008;</span></td><td class='border-r border-white px-2 py-1'><span class="text-green-500 font-bold">&#10004; 190</span></td></tr>
<tr data-empresa="CERVEJARIA HRX LTDA"><td class="border-r border-white px-2 py-1 whitespace-nowrap bg-gray-900 text-gray-100">HECTOR 5 ROUNDS</td><td class='border-r border-white px-2 py-1'><span class="text-green-500 font-bold">&#10004; 5</span></td><td class='border-r border-white px-2 py-1'><span class="text-red-500 font-bold">&#10008;</span></td><td class='border-r border-white px-2 py-1'><span class="text-red-500 font-bold">&#10008;</span></td><td class='border-r border-white px-2 py-1'><span class="text-red-500 font-bold">&#10008;</span></td><td class='border-r border-white px-2 py-1'><span class="text-green-500 font-bold">&#10004; 2</span></td></tr>
<tr data-empresa="CERVEJARIA HRX LTDA"><td class="border-r border-white px-2 py-1 whitespace-nowrap bg-gray-900 text-gray-100">HERMES E RENATO</td><td class='border-r border-white px-2 py-1'><span class="text-red-500 font-bold">&#10008;</span></td><td class='border-r border-white px-2 py-1'><span class="text-red-500 font-bold">&#10008;</span></td><td class='border-r border-white px-2 py-1'><span class="text-red-500 font-bold">&#10008;</span></td><td class='border-r border-white px-2 py-1'><span class="text-green-500 font-bold">&#10004; 175</span></td><td class='border-r border-white px-2 py-1'><span class="text-red-500 font-bold">&#10008;</span></td></tr>
<tr data-empresa="CERVEJARIA HRX LTDA"><td class="border-r border-white px-2 py-1 whitespace-nowrap bg-gray-900 text-gray-100">JEAN LE BLANC</td><td class='border-r border-white px-2 py-1'><span class="text-red-500 font-bold">&#10008;</span></td><td class='border-r border-white px-2 py-1'><span class="text-red-500 font-bold">&#10008;</span></td><td class='border-r border-white px-2 py-1'><span class="text-green-500 font-bold">&#10004; 1</span></td><td class='border-r border-white px-2 py-1'><span class="text-red-500 font-bold">&#10008;</span></td><td class='border-r border-white px-2 py-1'><span class="text-green-500 font-bold">&#10004; 435</span></td></tr>
<tr data-empresa="CERVEJARIA HRX LTDA"><td class="border-r border-white px-2 py-1 whitespace-nowrap bg-gray-900 text-gray-100">JUICY JILL</td><td class='border-r border-white px-2 py-1'><span class="text-green-500 font-bold">&#10004; 17</span></td><td class='border-r border-white px-2 py-1'><span class="text-red-500 font-bold">&#10008;</span></td><td class='border-r border-white px-2 py-1'><span class="text-green-500 font-bold">&#10004; 2</span></td><td class='border-r border-white px-2 py-1'><span class="text-red-500 font-bold">&#10008;</span></td><td class='border-r border-white px-2 py-1'><span class="text-green-500 font-bold">&#10004; 600</span></td></tr>
<tr data-empresa="CERVEJARIA HRX LTDA"><td class="border-r border-white px-2 py-1 whitespace-nowrap bg-gray-900 text-gray-100">MARK THE PASCHOA</td><td class='border-r border-white px-2 py-1'><span class="text-red-500 font-bold">&#10008;</span></td><td class='border-r border-white px-2 py-1'><span class="text-red-500 font-bold">&#10008;</span></td><td class='border-r border-white px-2 py-1'><span class="text-red-500 font-bold">&#10008;</span></td><td class='border-r border-white px-2 py-1'><span class="text-red-500 font-bold">&#10008;</span></td><td class='border-r border-white px-2 py-1'><span class="text-green-500 font-bold">&#10004; 58</span></td></tr>
<tr data-empresa="CERVEJARIA HRX LTDA"><td class="border-r border-white px-2 py-1 whitespace-nowrap bg-gray-900 text-gray-100">MARK THE SHADOW</td><td class='border-r border-white px-2 py-1'><span class="text-green-500 font-bold">&#10004; 13</span></td><td class='border-r border-white px-2 py-1'><span class="text-red-500 font-bold">&#10008;</span></td><td class='border-r border-white px-2 py-1'><span class="text-red-500 font-bold">&#10008;</span></td><td class='border-r border-white px-2 py-1'><span class="text-red-500 font-bold">&#10008;</span></td><td class='border-r border-white px-2 py-1'><span class="text-green-500 font-bold">&#10004; 4</span></td></tr>
<tr data-empresa="CERVEJARIA HRX LTDA"><td class="border-r border-white px-2 py-1 whitespace-nowrap bg-gray-900 text-gray-100">OLD BUT GOLD</td><td class='border-r border-white px-2 py-1'><span class="text-green-500 font-bold">&#10004; 12</span></td><td class='border-r border-white px-2 py-1'><span class="text-red-500 font-bold">&#10008;</span></td><td class='border-r border-white px-2 py-1'><span class="text-red-500 font-bold">&#10008;</span></td><td class='border-r border-white px-2 py-1'><span class="text-red-500 font-bold">&#10008;</span></td><td class='border-r border-white px-2 py-1'><span class="text-red-500 font-bold">&#10008;</span></td></tr>
<tr data-empresa="CERVEJARIA HRX LTDA"><td class="border-r border-white px-2 py-1 whitespace-nowrap bg-gray-900 text-gray-100">PINA A VIVA</td><td class='border-r border-white px-2 py-1'><span class="text-red-500 font-bold">&#10008;</span></td><td class='border-r border-white px-2 py-1'><span class="text-red-500 font-bold">&#10008;</span></td><td class='border-r border-white px-2 py-1'><span class="text-red-500 font-bold">&#10008;</span></td><td class='border-r border-white px-2 py-1'><span class="text-red-500 font-bold">&#10008;</span></td><td class='border-r border-white px-2 py-1'><span class="text-green-500 font-bold">&#10004; 326</span></td></tr>
<tr data-empresa="CERVEJARIA HRX LTDA"><td class="border-r border-white px-2 py-1 whitespace-nowrap bg-gray-900 text-gray-100">RANNA RIDER</td><td class='border-r border-white px-2 py-1'><span class="text-green-500 font-bold">&#10004; 24</span></td><td class='border-r border-white px-2 py-1'><span class="text-red-500 font-bold">&#10008;</span></td><td class='border-r border-white px-2 py-1'><span class="text-red-500 font-bold">&#10008;</span></td><td class='border-r border-white px-2 py-1'><span class="text-red-500 font-bold">&#10008;</span></td><td class='border-r border-white px-2 py-1'><span class="text-green-500 font-bold">&#10004; 501</span></td></tr>
<tr data-empresa="CERVEJARIA HRX LTDA"><td class="border-r border-white px-2 py-1 whitespace-nowrap bg-gray-900 text-gray-100">WELT PILSEN</td><td class='border-r border-white px-2 py-1'><span class="text-green-500 font-bold">&#10004; 7</span></td><td class='border-r border-white px-2 py-1'><span class="text-green-500 font-bold">&#10004; 3</span></td><td class='border-r border-white px-2 py-1'><span class="text-red-500 font-bold">&#10008;</span></td><td class='border-r border-white px-2 py-1'><span class="text-red-500 font-bold">&#10008;</span></td><td class='border-r border-white px-2 py-1'><span class="text-red-500 font-bold">&#10008;</span></td></tr>
<tr data-empresa="CERVEJARIA HRX LTDA"><td class="border-r border-white px-2 py-1 whitespace-nowrap bg-gray-900 text-gray-100">WILLIE THE BITTER</td><td class='border-r border-white px-2 py-1'><span class="text-green-500 font-bold">&#10004; 21</span></td><td class='border-r border-white px-2 py-1'><span class="text-red-500 font-bold">&#10008;</span></td><td class='border-r border-white px-2 py-1'><span class="text-red-500 font-bold">&#10008;</span></td><td class='border-r border-white px-2 py-1'><span class="text-red-500 font-bold">&#10008;</span></td><td class='border-r border-white px-2 py-1'><span class="text-green-500 font-bold">&#10004; 553</span></td></tr>
<tr data-empresa="CERVEJARIA HRX LTDA"><td class="border-r border-white px-2 py-1 whitespace-nowrap bg-gray-900 text-gray-100">XP 093 BRISA DA MANHA</td><td class='border-r border-white px-2 py-1'><span class="text-red-500 font-bold">&#10008;</span></td><td class='border-r border-white px-2 py-1'><span class="text-red-500 font-bold">&#10008;</span></td><td class='border-r border-white px-2 py-1'><span class="text-red-500 font-bold">&#10008;</span></td><td class='border-r border-white px-2 py-1'><span class="text-red-500 font-bold">&#10008;</span></td><td class='border-r border-white px-2 py-1'><span class="text-green-500 font-bold">&#10004; 61</span></td></tr>
<tr data-empresa="CERVEJARIA HRX LTDA"><td class="border-r border-white px-2 py-1 whitespace-nowrap bg-gray-900 text-gray-100">XP 094 HOP HEADS</td><td class='border-r border-white px-2 py-1'><span class="text-green-500 font-bold">&#10004; 7</span></td><td class='border-r border-white px-2 py-1'><span class="text-red-500 font-bold">&#10008;</span></td><td class='border-r border-white px-2 py-1'><span class="text-red-500 font-bold">&#10008;</span></td><td class='border-r border-white px-2 py-1'><span class="text-red-500 font-bold">&#10008;</span></td><td class='border-r border-white px-2 py-1'><span class="text-green-500 font-bold">&#10004; 560</span></td></tr>
<tr data-empresa="CERVEJARIA HRX LTDA"><td class="border-r border-white px-2 py-1 whitespace-nowrap bg-gray-900 text-gray-100">ZE DO MORRO</td><td class='border-r border-white px-2 py-1'><span class="text-green-500 font-bold">&#10004; 13</span></td><td class='border-r border-white px-2 py-1'><span class="text-red-500 font-bold">&#10008;</span></td><td class='border-r border-white px-2 py-1'><span class="text-green-500 font-bold">&#10004; 2</span></td><td class='border-r border-white px-2 py-1'><span class="text-red-500 font-bold">&#10008;</span></td><td class='border-r border-white px-2 py-1'><span class="text-green-500 font-bold">&#10004; 23</span></td></tr>
<tr data-empresa="GO-BASTARDS BEBIDAS GO LTDA"><td class="border-r border-white px-2 py-1 whitespace-nowrap bg-gray-900 text-gray-100">ANNOYNG TORANJITO</td><td class='border-r border-white px-2 py-1'><span class="text-red-500 font-bold">&#10008;</span></td><td class='border-r border-white px-2 py-1'><span class="text-red-500 font-bold">&#10008;</span></td><td class='border-r border-white px-2 py-1'><span class="text-red-500 font-bold">&#10008;</span></td><td class='border-r border-white px-2 py-1'><span class="text-red-500 font-bold">&#10008;</span></td><td class='border-r border-white px-2 py-1'><span class="text-green-500 font-bold">&#10004; 3</span></td></tr>
<tr data-empresa="GO-BASTARDS BEBIDAS GO LTDA"><td class="border-r border-white px-2 py-1 whitespace-nowrap bg-gray-900 text-gray-100">CRIATURA DO PANTANO</td><td class='border-r border-white px-2 py-1'><span class="text-red-500 font-bold">&#10008;</span></td><td class='border-r border-white px-2 py-1'><span class="text-red-500 font-bold">&#10008;</span></td><td class='border-r border-white px-2 py-1'><span class="text-red-500 font-bold">&#10008;</span></td><td class='border-r border-white px-2 py-1'><span class="text-red-500 font-bold">&#10008;</span></td><td class='border-r border-white px-2 py-1'><span class="text-green-500 font-bold">&#10004; 6</span></td></tr>
<tr data-empresa="GO-BASTARDS BEBIDAS GO LTDA"><td class="border-r border-white px-2 py-1 whitespace-nowrap bg-gray-900 text-gray-100">HECTOR 5 ROUNDS</td><td class='border-r border-white px-2 py-1'><span class="text-red-500 font-bold">&#10008;</span></td><td class='border-r border-white px-2 py-1'><span class="text-red-500 font-bold">&#10008;</span></td><td class='border-r border-white px-2 py-1'><span class="text-red-500 font-bold">&#10008;</span></td><td class='border-r border-white px-2 py-1'><span class="text-red-500 font-bold">&#10008;</span></td><td class='border-r border-white px-2 py-1'><span class="text-green-500 font-bold">&#10004; 9</span></td></tr>
<tr data-empresa="GO-BASTARDS BEBIDAS GO LTDA"><td class="border-r border-white px-2 py-1 whitespace-nowrap bg-gray-900 text-gray-100">HERMES E RENATO</td><td class='border-r border-white px-2 py-1'><span class="text-red-500 font-bold">&#10008;</span></td><td class='border-r border-white px-2 py-1'><span class="text-red-500 font-bold">&#10008;</span></td><td class='border-r border-white px-2 py-1'><span class="text-red-500 font-bold">&#10008;</span></td><td class='border-r border-white px-2 py-1'><span class="text-green-500 font-bold">&#10004; 12</span></td><td class='border-r border-white px-2 py-1'><span class="text-red-500 font-bold">&#10008;</span></td></tr>
<tr data-empresa="GO-BASTARDS BEBIDAS GO LTDA"><td class="border-r border-white px-2 py-1 whitespace-nowrap bg-gray-900 text-gray-100">JEAN LE BLANC</td><td class='border-r border-white px-2 py-1'><span class="text-red-500 font-bold">&#10008;</span></td><td class='border-r border-white px-2 py-1'><span class="text-red-500 font-bold">&#10008;</span></td><td class='border-r border-white px-2 py-1'><span class="text-red-500 font-bold">&#10008;</span></td><td class='border-r border-white px-2 py-1'><span class="text-red-500 font-bold">&#10008;</span></td><td class='border-r border-white px-2 py-1'><span class="text-green-500 font-bold">&#10004; 2</span></td></tr>
<tr data-empresa="GO-BASTARDS BEBIDAS GO LTDA"><td class="border-r border-white px-2 py-1 whitespace-nowrap bg-gray-900 text-gray-100">JUICY JILL</td><td class='border-r border-white px-2 py-1'><span class="text-red-500 font-bold">&#10008;</span></td><td class='border-r border-white px-2 py-1'><span class="text-red-500 font-bold">&#10008;</span></td><td class='border-r border-white px-2 py-1'><span class="text-red-500 font-bold">&#10008;</span></td><td class='border-r border-white px-2 py-1'><span class="text-red-500 font-bold">&#10008;</span></td><td class='border-r border-white px-2 py-1'><span class="text-green-500 font-bold">&#10004; 8</span></td></tr>
<tr data-empresa="GO-BASTARDS BEBIDAS GO LTDA"><td class="border-r border-white px-2 py-1 whitespace-nowrap bg-gray-900 text-gray-100">MARK THE SHADOW</td><td class='border-r border-white px-2 py-1'><span class="text-red-500 font-bold">&#10008;</span></td><td class='border-r border-white px-2 py-1'><span class="text-red-500 font-bold">&#10008;</span></td><td class='border-r border-white px-2 py-1'><span class="text-red-500 font-bold">&#10008;</span></td><td class='border-r border-white px-2 py-1'><span class="text-red-500 font-bold">&#10008;</span></td><td class='border-r border-white px-2 py-1'><span class="text-green-500 font-bold">&#10004; 36</span></td></tr>
<tr data-empresa="GO-BASTARDS BEBIDAS GO LTDA"><td class="border-r border-white px-2 py-1 whitespace-nowrap bg-gray-900 text-gray-100">PEROLA NEGRA</td><td class='border-r border-white px-2 py-1'><span class="text-red-500 font-bold">&#10008;</span></td><td class='border-r border-white px-2 py-1'><span class="text-red-500 font-bold">&#10008;</span></td><td class='border-r border-white px-2 py-1'><span class="text-red-500 font-bold">&#10008;</span></td><td class='border-r border-white px-2 py-1'><span class="text-red-500 font-bold">&#10008;</span></td><td class='border-r border-white px-2 py-1'><span class="text-green-500 font-bold">&#10004; 30</span></td></tr>
<tr data-empresa="GO-BASTARDS BEBIDAS GO LTDA"><td class="border-r border-white px-2 py-1 whitespace-nowrap bg-gray-900 text-gray-100">RANNA RIDER</td><td class='border-r border-white px-2 py-1'><span class="text-red-500 font-bold">&#10008;</span></td><td class='border-r border-white px-2 py-1'><span class="text-red-500 font-bold">&#10008;</span></td><td class='border-r border-white px-2 py-1'><span class="text-red-500 font-bold">&#10008;</span></td><td class='border-r border-white px-2 py-1'><span class="text-red-500 font-bold">&#10008;</span></td><td class='border-r border-white px-2 py-1'><span class="text-green-500 font-bold">&#10004; 12</span></td></tr>
<tr data-empresa="GO-BASTARDS BEBIDAS GO LTDA"><td class="border-r border-white px-2 py-1 whitespace-nowrap bg-gray-900 text-gray-100">UM BRINDE A ELAS</td><td class='border-r border-white px-2 py-1'><span class="text-red-500 font-bold">&#10008;</span></td><td class='border-r border-white px-2 py-1'><span class="text-red-500 font-bold">&#10008;</span></td><td class='border-r border-white px-2 py-1'><span class="text-red-500 font-bold">&#10008;</span></td><td class='border-r border-white px-2 py-1'><span class="text-red-500 font-bold">&#10008;</span></td><td class='border-r border-white px-2 py-1'><span class="text-green-500 font-bold">&#10004; 3</span></td></tr>
<tr data-empresa="GO-BASTARDS BEBIDAS GO LTDA"><td class="border-r border-white px-2 py-1 whitespace-nowrap bg-gray-900 text-gray-100">WILLIE THE BITTER</td><td class='border-r border-white px-2 py-1'><span class="text-red-500 font-bold">&#10008;</span></td><td class='border-r border-white px-2 py-1'><span class="text-red-500 font-bold">&#10008;</span></td><td class='border-r border-white px-2 py-1'><span class="text-red-500 font-bold">&#10008;</span></td><td class='border-r border-white px-2 py-1'><span class="text-red-500 font-bold">&#10008;</span></td><td class='border-r border-white px-2 py-1'><span class="text-green-500 font-bold">&#10004; 30</span></td></tr>
<tr data-empresa="GO-BASTARDS BEBIDAS GO LTDA"><td class="border-r border-white px-2 py-1 whitespace-nowrap bg-gray-900 text-gray-100">XP 091 ORANGE IPA</td><td class='border-r border-white px-2 py-1'><span class="text-red-500 font-bold">&#10008;</span></td><td class='border-r border-white px-2 py-1'><span class="text-red-500 font-bold">&#10008;</span></td><td class='border-r border-white px-2 py-1'><span class="text-red-500 font-bold">&#10008;</span></td><td class='border-r border-white px-2 py-1'><span class="text-red-500 font-bold">&#10008;</span></td><td class='border-r border-white px-2 py-1'><span class="text-green-500 font-bold">&#10004; 5</span></td></tr>
<tr data-empresa="GO-BASTARDS BEBIDAS GO LTDA"><td class="border-r border-white px-2 py-1 whitespace-nowrap bg-gray-900 text-gray-100">XP 094 HOP HEADS</td><td class='border-r border-white px-2 py-1'><span class="text-red-500 font-bold">&#10008;</span></td><td class='border-r border-white px-2 py-1'><span class="text-red-500 font-bold">&#10008;</span></td><td class='border-r border-white px-2 py-1'><span class="text-red-500 font-bold">&#10008;</span></td><td class='border-r border-white px-2 py-1'><span class="text-red-500 font-bold">&#10008;</span></td><td class='border-r border-white px-2 py-1'><span class="text-green-500 font-bold">&#10004; 24</span></td></tr>
<tr data-empresa="IND. XAMA"><td class="border-r border-white px-2 py-1 whitespace-nowrap bg-gray-900 text-gray-100">ACID BLOOD</td><td class='border-r border-white px-2 py-1'><span class="text-red-500 font-bold">&#10008;</span></td><td class='border-r border-white px-2 py-1'><span class="text-red-500 font-bold">&#10008;</span></td><td class='border-r border-white px-2 py-1'><span class="text-red-500 font-bold">&#10008;</span></td><td class='border-r border-white px-2 py-1'><span class="text-red-500 font-bold">&#10008;</span></td><td class='border-r border-white px-2 py-1'><span class="text-green-500 font-bold">&#10004; 562</span></td></tr>
<tr data-empresa="IND. XAMA"><td class="border-r border-white px-2 py-1 whitespace-nowrap bg-gray-900 text-gray-100">HECTOR 5 ROUNDS</td><td class='border-r border-white px-2 py-1'><span class="text-red-500 font-bold">&#10008;</span></td><td class='border-r border-white px-2 py-1'><span class="text-green-500 font-bold">&#10004; 4</span></td><td class='border-r border-white px-2 py-1'><span class="text-red-500 font-bold">&#10008;</span></td><td class='border-r border-white px-2 py-1'><span class="text-red-500 font-bold">&#10008;</span></td><td class='border-r border-white px-2 py-1'><span class="text-red-500 font-bold">&#10008;</span></td></tr>
<tr data-empresa="IND. XAMA"><td class="border-r border-white px-2 py-1 whitespace-nowrap bg-gray-900 text-gray-100">JUICY JILL</td><td class='border-r border-white px-2 py-1'><span class="text-red-500 font-bold">&#10008;</span></td><td class='border-r border-white px-2 py-1'><span class="text-red-500 font-bold">&#10008;</span></td><td class='border-r border-white px-2 py-1'><span class="text-red-500 font-bold">&#10008;</span></td><td class='border-r border-white px-2 py-1'><span class="text-red-500 font-bold">&#10008;</span></td><td class='border-r border-white px-2 py-1'><span class="text-green-500 font-bold">&#10004; 25</span></td></tr>
<tr data-empresa="IND. XAMA"><td class="border-r border-white px-2 py-1 whitespace-nowrap bg-gray-900 text-gray-100">ZE DO MORRO</td><td class='border-r border-white px-2 py-1'><span class="text-red-500 font-bold">&#10008;</span></td><td class='border-r border-white px-2 py-1'><span class="text-green-500 font-bold">&#10004; 6</span></td><td class='border-r border-white px-2 py-1'><span class="text-red-500 font-bold">&#10008;</span></td><td class='border-r border-white px-2 py-1'><span class="text-red-500 font-bold">&#10008;</span></td><td class='border-r border-white px-2 py-1'><span class="text-red-500 font-bold">&#10008;</span></td></tr>
<tr data-empresa="MG-BASTARDS BEBIDAS MG LTDA"><td class="border-r border-white px-2 py-1 whitespace-nowrap bg-gray-900 text-gray-100">CRIATURA DO PANTANO</td><td class='border-r border-white px-2 py-1'><span class="text-red-500 font-bold">&#10008;</span></td><td class='border-r border-white px-2 py-1'><span class="text-red-500 font-bold">&#10008;</span></td><td class='border-r border-white px-2 py-1'><span class="text-green-500 font-bold">&#10004; 1</span></td><td class='border-r border-white px-2 py-1'><span class="text-red-500 font-bold">&#10008;</span></td><td class='border-r border-white px-2 py-1'><span class="text-green-500 font-bold">&#10004; 12</span></td></tr>
<tr data-empresa="MG-BASTARDS BEBIDAS MG LTDA"><td class="border-r border-white px-2 py-1 whitespace-nowrap bg-gray-900 text-gray-100">DOG SAVE THE BEER</td><td class='border-r border-white px-2 py-1'><span class="text-red-500 font-bold">&#10008;</span></td><td class='border-r border-white px-2 py-1'><span class="text-red-500 font-bold">&#10008;</span></td><td class='border-r border-white px-2 py-1'><span class="text-green-500 font-bold">&#10004; 2</span></td><td class='border-r border-white px-2 py-1'><span class="text-red-500 font-bold">&#10008;</span></td><td class='border-r border-white px-2 py-1'><span class="text-red-500 font-bold">&#10008;</span></td></tr>
<tr data-empresa="MG-BASTARDS BEBIDAS MG LTDA"><td class="border-r border-white px-2 py-1 whitespace-nowrap bg-gray-900 text-gray-100">HECTOR 5 ROUNDS</td><td class='border-r border-white px-2 py-1'><span class="text-red-500 font-bold">&#10008;</span></td><td class='border-r border-white px-2 py-1'><span class="text-red-500 font-bold">&#10008;</span></td><td class='border-r border-white px-2 py-1'><span class="text-green-500 font-bold">&#10004; 3</span></td><td class='border-r border-white px-2 py-1'><span class="text-red-500 font-bold">&#10008;</span></td><td class='border-r border-white px-2 py-1'><span class="text-red-500 font-bold">&#10008;</span></td></tr>
<tr data-empresa="MG-BASTARDS BEBIDAS MG LTDA"><td class="border-r border-white px-2 py-1 whitespace-nowrap bg-gray-900 text-gray-100">HERMES E RENATO</td><td class='border-r border-white px-2 py-1'><span class="text-red-500 font-bold">&#10008;</span></td><td class='border-r border-white px-2 py-1'><span class="text-red-500 font-bold">&#10008;</span></td><td class='border-r border-white px-2 py-1'><span class="text-red-500 font-bold">&#10008;</span></td><td class='border-r border-white px-2 py-1'><span class="text-green-500 font-bold">&#10004; 24</span></td><td class='border-r border-white px-2 py-1'><span class="text-red-500 font-bold">&#10008;</span></td></tr>
<tr data-empresa="MG-BASTARDS BEBIDAS MG LTDA"><td class="border-r border-white px-2 py-1 whitespace-nowrap bg-gray-900 text-gray-100">MARK THE SHADOW</td><td class='border-r border-white px-2 py-1'><span class="text-red-500 font-bold">&#10008;</span></td><td class='border-r border-white px-2 py-1'><span class="text-red-500 font-bold">&#10008;</span></td><td class='border-r border-white px-2 py-1'><span class="text-green-500 font-bold">&#10004; 2</span></td><td class='border-r border-white px-2 py-1'><span class="text-red-500 font-bold">&#10008;</span></td><td class='border-r border-white px-2 py-1'><span class="text-green-500 font-bold">&#10004; 12</span></td></tr>
<tr data-empresa="MG-BASTARDS BEBIDAS MG LTDA"><td class="border-r border-white px-2 py-1 whitespace-nowrap bg-gray-900 text-gray-100">PINA A VIVA</td><td class='border-r border-white px-2 py-1'><span class="text-red-500 font-bold">&#10008;</span></td><td class='border-r border-white px-2 py-1'><span class="text-red-500 font-bold">&#10008;</span></td><td class='border-r border-white px-2 py-1'><span class="text-red-500 font-bold">&#10008;</span></td><td class='border-r border-white px-2 py-1'><span class="text-red-500 font-bold">&#10008;</span></td><td class='border-r border-white px-2 py-1'><span class="text-green-500 font-bold">&#10004; 12</span></td></tr>
<tr data-empresa="MG-BASTARDS BEBIDAS MG LTDA"><td class="border-r border-white px-2 py-1 whitespace-nowrap bg-gray-900 text-gray-100">RANNA RIDER</td><td class='border-r border-white px-2 py-1'><span class="text-red-500 font-bold">&#10008;</span></td><td class='border-r border-white px-2 py-1'><span class="text-red-500 font-bold">&#10008;</span></td><td class='border-r border-white px-2 py-1'><span class="text-green-500 font-bold">&#10004; 3</span></td><td class='border-r border-white px-2 py-1'><span class="text-red-500 font-bold">&#10008;</span></td><td class='border-r border-white px-2 py-1'><span class="text-green-500 font-bold">&#10004; 12</span></td></tr>
<tr data-empresa="MG-BASTARDS BEBIDAS MG LTDA"><td class="border-r border-white px-2 py-1 whitespace-nowrap bg-gray-900 text-gray-100">WILLIE THE BITTER</td><td class='border-r border-white px-2 py-1'><span class="text-red-500 font-bold">&#10008;</span></td><td class='border-r border-white px-2 py-1'><span class="text-red-500 font-bold">&#10008;</span></td><td class='border-r border-white px-2 py-1'><span class="text-green-500 font-bold">&#10004; 2</span></td><td class='border-r border-white px-2 py-1'><span class="text-red-500 font-bold">&#10008;</span></td><td class='border-r border-white px-2 py-1'><span class="text-green-500 font-bold">&#10004; 24</span></td></tr>
<tr data-empresa="MG-BASTARDS BEBIDAS MG LTDA"><td class="border-r border-white px-2 py-1 whitespace-nowrap bg-gray-900 text-gray-100">XP 093 BRISA DA MANHA</td><td class='border-r border-white px-2 py-1'><span class="text-red-500 font-bold">&#10008;</span></td><td class='border-r border-white px-2 py-1'><span class="text-red-500 font-bold">&#10008;</span></td><td class='border-r border-white px-2 py-1'><span class="text-green-500 font-bold">&#10004; 1</span></td><td class='border-r border-white px-2 py-1'><span class="text-red-500 font-bold">&#10008;</span></td><td class='border-r border-white px-2 py-1'><span class="text-red-500 font-bold">&#10008;</span></td></tr>
<tr data-empresa="MG-BASTARDS BEBIDAS MG LTDA"><td class="border-r border-white px-2 py-1 whitespace-nowrap bg-gray-900 text-gray-100">XP 094 HOP HEADS</td><td class='border-r border-white px-2 py-1'><span class="text-red-500 font-bold">&#10008;</span></td><td class='border-r border-white px-2 py-1'><span class="text-red-500 font-bold">&#10008;</span></td><td class='border-r border-white px-2 py-1'><span class="text-red-500 font-bold">&#10008;</span></td><td class='border-r border-white px-2 py-1'><span class="text-red-500 font-bold">&#10008;</span></td><td class='border-r border-white px-2 py-1'><span class="text-green-500 font-bold">&#10004; 24</span></td></tr>
<tr data-empresa="MG-BASTARDS BEBIDAS MG LTDA"><td class="border-r border-white px-2 py-1 whitespace-nowrap bg-gray-900 text-gray-100">XP 095 BROWN IPA</td><td class='border-r border-white px-2 py-1'><span class="text-red-500 font-bold">&#10008;</span></td><td class='border-r border-white px-2 py-1'><span class="text-red-500 font-bold">&#10008;</span></td><td class='border-r border-white px-2 py-1'><span class="text-green-500 font-bold">&#10004; 1</span></td><td class='border-r border-white px-2 py-1'><span class="text-red-500 font-bold">&#10008;</span></td><td class='border-r border-white px-2 py-1'><span class="text-red-500 font-bold">&#10008;</span></td></tr>
<tr data-empresa="MG-BASTARDS BEBIDAS MG LTDA"><td class="border-r border-white px-2 py-1 whitespace-nowrap bg-gray-900 text-gray-100">ZE DO MORRO</td><td class='border-r border-white px-2 py-1'><span class="text-red-500 font-bold">&#10008;</span></td><td class='border-r border-white px-2 py-1'><span class="text-red-500 font-bold">&#10008;</span></td><td class='border-r border-white px-2 py-1'><span class="text-green-500 font-bold">&#10004; 2</span></td><td class='border-r border-white px-2 py-1'><span class="text-red-500 font-bold">&#10008;</span></td><td class='border-r border-white px-2 py-1'><span class="text-red-500 font-bold">&#10008;</span></td></tr>
<tr data-empresa="RJ-BASTARDS BEBIDAS RJ LTDA"><td class="border-r border-white px-2 py-1 whitespace-nowrap bg-gray-900 text-gray-100">ANNOYNG TORANJITO</td><td class='border-r border-white px-2 py-1'><span class="text-red-500 font-bold">&#10008;</span></td><td class='border-r border-white px-2 py-1'><span class="text-red-500 font-bold">&#10008;</span></td><td class='border-r border-white px-2 py-1'><span class="text-red-500 font-bold">&#10008;</span></td><td class='border-r border-white px-2 py-1'><span class="text-red-500 font-bold">&#10008;</span></td><td class='border-r border-white px-2 py-1'><span class="text-green-500 font-bold">&#10004; 2</span></td></tr>
<tr data-empresa="RJ-BASTARDS BEBIDAS RJ LTDA"><td class="border-r border-white px-2 py-1 whitespace-nowrap bg-gray-900 text-gray-100">CRIATURA DO PANTANO</td><td class='border-r border-white px-2 py-1'><span class="text-red-500 font-bold">&#10008;</span></td><td class='border-r border-white px-2 py-1'><span class="text-red-500 font-bold">&#10008;</span></td><td class='border-r border-white px-2 py-1'><span class="text-red-500 font-bold">&#10008;</span></td><td class='border-r border-white px-2 py-1'><span class="text-red-500 font-bold">&#10008;</span></td><td class='border-r border-white px-2 py-1'><span class="text-green-500 font-bold">&#10004; 74</span></td></tr>
<tr data-empresa="RJ-BASTARDS BEBIDAS RJ LTDA"><td class="border-r border-white px-2 py-1 whitespace-nowrap bg-gray-900 text-gray-100">DOG SAVE THE BEER</td><td class='border-r border-white px-2 py-1'><span class="text-red-500 font-bold">&#10008;</span></td><td class='border-r border-white px-2 py-1'><span class="text-red-500 font-bold">&#10008;</span></td><td class='border-r border-white px-2 py-1'><span class="text-red-500 font-bold">&#10008;</span></td><td class='border-r border-white px-2 py-1'><span class="text-red-500 font-bold">&#10008;</span></td><td class='border-r border-white px-2 py-1'><span class="text-green-500 font-bold">&#10004; 120</span></td></tr>
<tr data-empresa="RJ-BASTARDS BEBIDAS RJ LTDA"><td class="border-r border-white px-2 py-1 whitespace-nowrap bg-gray-900 text-gray-100">HECTOR 5 ROUNDS</td><td class='border-r border-white px-2 py-1'><span class="text-red-500 font-bold">&#10008;</span></td><td class='border-r border-white px-2 py-1'><span class="text-red-500 font-bold">&#10008;</span></td><td class='border-r border-white px-2 py-1'><span class="text-green-500 font-bold">&#10004; 4</span></td><td class='border-r border-white px-2 py-1'><span class="text-red-500 font-bold">&#10008;</span></td><td class='border-r border-white px-2 py-1'><span class="text-green-500 font-bold">&#10004; 198</span></td></tr>
<tr data-empresa="RJ-BASTARDS BEBIDAS RJ LTDA"><td class="border-r border-white px-2 py-1 whitespace-nowrap bg-gray-900 text-gray-100">HERMES E RENATO</td><td class='border-r border-white px-2 py-1'><span class="text-red-500 font-bold">&#10008;</span></td><td class='border-r border-white px-2 py-1'><span class="text-red-500 font-bold">&#10008;</span></td><td class='border-r border-white px-2 py-1'><span class="text-green-500 font-bold">&#10004; 3</span></td><td class='border-r border-white px-2 py-1'><span class="text-green-500 font-bold">&#10004; 72</span></td><td class='border-r border-white px-2 py-1'><span class="text-red-500 font-bold">&#10008;</span></td></tr>
<tr data-empresa="RJ-BASTARDS BEBIDAS RJ LTDA"><td class="border-r border-white px-2 py-1 whitespace-nowrap bg-gray-900 text-gray-100">JEAN LE BLANC</td><td class='border-r border-white px-2 py-1'><span class="text-red-500 font-bold">&#10008;</span></td><td class='border-r border-white px-2 py-1'><span class="text-red-500 font-bold">&#10008;</span></td><td class='border-r border-white px-2 py-1'><span class="text-green-500 font-bold">&#10004; 2</span></td><td class='border-r border-white px-2 py-1'><span class="text-red-500 font-bold">&#10008;</span></td><td class='border-r border-white px-2 py-1'><span class="text-red-500 font-bold">&#10008;</span></td></tr>
<tr data-empresa="RJ-BASTARDS BEBIDAS RJ LTDA"><td class="border-r border-white px-2 py-1 whitespace-nowrap bg-gray-900 text-gray-100">JUICY JILL</td><td class='border-r border-white px-2 py-1'><span class="text-red-500 font-bold">&#10008;</span></td><td class='border-r border-white px-2 py-1'><span class="text-red-500 font-bold">&#10008;</span></td><td class='border-r border-white px-2 py-1'><span class="text-green-500 font-bold">&#10004; 2</span></td><td class='border-r border-white px-2 py-1'><span class="text-red-500 font-bold">&#10008;</span></td><td class='border-r border-white px-2 py-1'><span class="text-green-500 font-bold">&#10004; 48</span></td></tr>
<tr data-empresa="RJ-BASTARDS BEBIDAS RJ LTDA"><td class="border-r border-white px-2 py-1 whitespace-nowrap bg-gray-900 text-gray-100">MARK THE SHADOW</td><td class='border-r border-white px-2 py-1'><span class="text-red-500 font-bold">&#10008;</span></td><td class='border-r border-white px-2 py-1'><span class="text-red-500 font-bold">&#10008;</span></td><td class='border-r border-white px-2 py-1'><span class="text-green-500 font-bold">&#10004; 3</span></td><td class='border-r border-white px-2 py-1'><span class="text-red-500 font-bold">&#10008;</span></td><td class='border-r border-white px-2 py-1'><span class="text-green-500 font-bold">&#10004; 28</span></td></tr>
<tr data-empresa="RJ-BASTARDS BEBIDAS RJ LTDA"><td class="border-r border-white px-2 py-1 whitespace-nowrap bg-gray-900 text-gray-100">PINA A VIVA</td><td class='border-r border-white px-2 py-1'><span class="text-red-500 font-bold">&#10008;</span></td><td class='border-r border-white px-2 py-1'><span class="text-red-500 font-bold">&#10008;</span></td><td class='border-r border-white px-2 py-1'><span class="text-red-500 font-bold">&#10008;</span></td><td class='border-r border-white px-2 py-1'><span class="text-red-500 font-bold">&#10008;</span></td><td class='border-r border-white px-2 py-1'><span class="text-green-500 font-bold">&#10004; 18</span></td></tr>
<tr data-empresa="RJ-BASTARDS BEBIDAS RJ LTDA"><td class="border-r border-white px-2 py-1 whitespace-nowrap bg-gray-900 text-gray-100">RANNA RIDER</td><td class='border-r border-white px-2 py-1'><span class="text-red-500 font-bold">&#10008;</span></td><td class='border-r border-white px-2 py-1'><span class="text-red-500 font-bold">&#10008;</span></td><td class='border-r border-white px-2 py-1'><span class="text-green-500 font-bold">&#10004; 3</span></td><td class='border-r border-white px-2 py-1'><span class="text-red-500 font-bold">&#10008;</span></td><td class='border-r border-white px-2 py-1'><span class="text-green-500 font-bold">&#10004; 12</span></td></tr>
<tr data-empresa="RJ-BASTARDS BEBIDAS RJ LTDA"><td class="border-r border-white px-2 py-1 whitespace-nowrap bg-gray-900 text-gray-100">UM BRINDE A ELAS</td><td class='border-r border-white px-2 py-1'><span class="text-red-500 font-bold">&#10008;</span></td><td class='border-r border-white px-2 py-1'><span class="text-red-500 font-bold">&#10008;</span></td><td class='border-r border-white px-2 py-1'><span class="text-red-500 font-bold">&#10008;</span></td><td class='border-r border-white px-2 py-1'><span class="text-red-500 font-bold">&#10008;</span></td><td class='border-r border-white px-2 py-1'><span class="text-green-500 font-bold">&#10004; 48</span></td></tr>
<tr data-empresa="RJ-BASTARDS BEBIDAS RJ LTDA"><td class="border-r border-white px-2 py-1 whitespace-nowrap bg-gray-900 text-gray-100">WELT RED ALE</td><td class='border-r border-white px-2 py-1'><span class="text-red-500 font-bold">&#10008;</span></td><td class='border-r border-white px-2 py-1'><span class="text-red-500 font-bold">&#10008;</span></td><td class='border-r border-white px-2 py-1'><span class="text-green-500 font-bold">&#10004; 1</span></td><td class='border-r border-white px-2 py-1'><span class="text-red-500 font-bold">&#10008;</span></td><td class='border-r border-white px-2 py-1'><span class="text-red-500 font-bold">&#10008;</span></td></tr>
<tr data-empresa="RJ-BASTARDS BEBIDAS RJ LTDA"><td class="border-r border-white px-2 py-1 whitespace-nowrap bg-gray-900 text-gray-100">WILLIE THE BITTER</td><td class='border-r border-white px-2 py-1'><span class="text-red-500 font-bold">&#10008;</span></td><td class='border-r border-white px-2 py-1'><span class="text-red-500 font-bold">&#10008;</span></td><td class='border-r border-white px-2 py-1'><span class="text-green-500 font-bold">&#10004; 1</span></td><td class='border-r border-white px-2 py-1'><span class="text-red-500 font-bold">&#10008;</span></td><td class='border-r border-white px-2 py-1'><span class="text-green-500 font-bold">&#10004; 102</span></td></tr>
<tr data-empresa="RJ-BASTARDS BEBIDAS RJ LTDA"><td class="border-r border-white px-2 py-1 whitespace-nowrap bg-gray-900 text-gray-100">XP 084 COCONUT BURST</td><td class='border-r border-white px-2 py-1'><span class="text-red-500 font-bold">&#10008;</span></td><td class='border-r border-white px-2 py-1'><span class="text-red-500 font-bold">&#10008;</span></td><td class='border-r border-white px-2 py-1'><span class="text-red-500 font-bold">&#10008;</span></td><td class='border-r border-white px-2 py-1'><span class="text-red-500 font-bold">&#10008;</span></td><td class='border-r border-white px-2 py-1'><span class="text-green-500 font-bold">&#10004; 48</span></td></tr>
<tr data-empresa="RJ-BASTARDS BEBIDAS RJ LTDA"><td class="border-r border-white px-2 py-1 whitespace-nowrap bg-gray-900 text-gray-100">XP 093 BRISA DA MANHA</td><td class='border-r border-white px-2 py-1'><span class="text-red-500 font-bold">&#10008;</span></td><td class='border-r border-white px-2 py-1'><span class="text-red-500 font-bold">&#10008;</span></td><td class='border-r border-white px-2 py-1'><span class="text-green-500 font-bold">&#10004; 2</span></td><td class='border-r border-white px-2 py-1'><span class="text-red-500 font-bold">&#10008;</span></td><td class='border-r border-white px-2 py-1'><span class="text-red-500 font-bold">&#10008;</span></td></tr>
<tr data-empresa="RJ-BASTARDS BEBIDAS RJ LTDA"><td class="border-r border-white px-2 py-1 whitespace-nowrap bg-gray-900 text-gray-100">XP 094 HOP HEADS</td><td class='border-r border-white px-2 py-1'><span class="text-red-500 font-bold">&#10008;</span></td><td class='border-r border-white px-2 py-1'><span class="text-red-500 font-bold">&#10008;</span></td><td class='border-r border-white px-2 py-1'><span class="text-green-500 font-bold">&#10004; 2</span></td><td class='border-r border-white px-2 py-1'><span class="text-red-500 font-bold">&#10008;</span></td><td class='border-r border-white px-2 py-1'><span class="text-red-500 font-bold">&#10008;</span></td></tr>
<tr data-empresa="RJ-BASTARDS BEBIDAS RJ LTDA"><td class="border-r border-white px-2 py-1 whitespace-nowrap bg-gray-900 text-gray-100">XP 095 BROWN IPA</td><td class='border-r border-white px-2 py-1'><span class="text-red-500 font-bold">&#10008;</span></td><td class='border-r border-white px-2 py-1'><span class="text-red-500 font-bold">&#10008;</span></td><td class='border-r border-white px-2 py-1'><span class="text-green-500 font-bold">&#10004; 1</span></td><td class='border-r border-white px-2 py-1'><span class="text-red-500 font-bold">&#10008;</span></td><td class='border-r border-white px-2 py-1'><span class="text-green-500 font-bold">&#10004; 12</span></td></tr>
<tr data-empresa="RJ-BASTARDS BEBIDAS RJ LTDA"><td class="border-r border-white px-2 py-1 whitespace-nowrap bg-gray-900 text-gray-100">ZE DO MORRO</td><td class='border-r border-white px-2 py-1'><span class="text-red-500 font-bold">&#10008;</span></td><td class='border-r border-white px-2 py-1'><span class="text-red-500 font-bold">&#10008;</span></td><td class='border-r border-white px-2 py-1'><span class="text-green-500 font-bold">&#10004; 2</span></td><td class='border-r border-white px-2 py-1'><span class="text-red-500 font-bold">&#10008;</span></td><td class='border-r border-white px-2 py-1'><span class="text-red-500 font-bold">&#10008;</span></td></tr>
<tr data-empresa="SC-BASTARDS BEBIDAS SC LTDA"><td class="border-r border-white px-2 py-1 whitespace-nowrap bg-gray-900 text-gray-100">ACID BLOOD</td><td class='border-r border-white px-2 py-1'><span class="text-green-500 font-bold">&#10004; 2</span></td><td class='border-r border-white px-2 py-1'><span class="text-red-500 font-bold">&#10008;</span></td><td class='border-r border-white px-2 py-1'><span class="text-red-500 font-bold">&#10008;</span></td><td class='border-r border-white px-2 py-1'><span class="text-red-500 font-bold">&#10008;</span></td><td class='border-r border-white px-2 py-1'><span class="text-red-500 font-bold">&#10008;</span></td></tr>
<tr data-empresa="SC-BASTARDS BEBIDAS SC LTDA"><td class="border-r border-white px-2 py-1 whitespace-nowrap bg-gray-900 text-gray-100">ANNOYNG TORANJITO</td><td class='border-r border-white px-2 py-1'><span class="text-red-500 font-bold">&#10008;</span></td><td class='border-r border-white px-2 py-1'><span class="text-red-500 font-bold">&#10008;</span></td><td class='border-r border-white px-2 py-1'><span class="text-red-500 font-bold">&#10008;</span></td><td class='border-r border-white px-2 py-1'><span class="text-red-500 font-bold">&#10008;</span></td><td class='border-r border-white px-2 py-1'><span class="text-green-500 font-bold">&#10004; 4</span></td></tr>
<tr data-empresa="SC-BASTARDS BEBIDAS SC LTDA"><td class="border-r border-white px-2 py-1 whitespace-nowrap bg-gray-900 text-gray-100">CRIATURA DO PANTANO</td><td class='border-r border-white px-2 py-1'><span class="text-green-500 font-bold">&#10004; 1</span></td><td class='border-r border-white px-2 py-1'><span class="text-red-500 font-bold">&#10008;</span></td><td class='border-r border-white px-2 py-1'><span class="text-green-500 font-bold">&#10004; 3</span></td><td class='border-r border-white px-2 py-1'><span class="text-red-500 font-bold">&#10008;</span></td><td class='border-r border-white px-2 py-1'><span class="text-green-500 font-bold">&#10004; 12</span></td></tr>
<tr data-empresa="SC-BASTARDS BEBIDAS SC LTDA"><td class="border-r border-white px-2 py-1 whitespace-nowrap bg-gray-900 text-gray-100">DOG SAVE THE BEER</td><td class='border-r border-white px-2 py-1'><span class="text-red-500 font-bold">&#10008;</span></td><td class='border-r border-white px-2 py-1'><span class="text-red-500 font-bold">&#10008;</span></td><td class='border-r border-white px-2 py-1'><span class="text-green-500 font-bold">&#10004; 2</span></td><td class='border-r border-white px-2 py-1'><span class="text-red-500 font-bold">&#10008;</span></td><td class='border-r border-white px-2 py-1'><span class="text-green-500 font-bold">&#10004; 27</span></td></tr>
<tr data-empresa="SC-BASTARDS BEBIDAS SC LTDA"><td class="border-r border-white px-2 py-1 whitespace-nowrap bg-gray-900 text-gray-100">HECTOR 5 ROUNDS</td><td class='border-r border-white px-2 py-1'><span class="text-green-500 font-bold">&#10004; 1</span></td><td class='border-r border-white px-2 py-1'><span class="text-red-500 font-bold">&#10008;</span></td><td class='border-r border-white px-2 py-1'><span class="text-green-500 font-bold">&#10004; 1</span></td><td class='border-r border-white px-2 py-1'><span class="text-red-500 font-bold">&#10008;</span></td><td class='border-r border-white px-2 py-1'><span class="text-green-500 font-bold">&#10004; 17</span></td></tr>
<tr data-empresa="SC-BASTARDS BEBIDAS SC LTDA"><td class="border-r border-white px-2 py-1 whitespace-nowrap bg-gray-900 text-gray-100">HERMES E RENATO</td><td class='border-r border-white px-2 py-1'><span class="text-green-500 font-bold">&#10004; 4</span></td><td class='border-r border-white px-2 py-1'><span class="text-red-500 font-bold">&#10008;</span></td><td class='border-r border-white px-2 py-1'><span class="text-green-500 font-bold">&#10004; 3</span></td><td class='border-r border-white px-2 py-1'><span class="text-red-500 font-bold">&#10008;</span></td><td class='border-r border-white px-2 py-1'><span class="text-red-500 font-bold">&#10008;</span></td></tr>
<tr data-empresa="SC-BASTARDS BEBIDAS SC LTDA"><td class="border-r border-white px-2 py-1 whitespace-nowrap bg-gray-900 text-gray-100">JEAN LE BLANC</td><td class='border-r border-white px-2 py-1'><span class="text-green-500 font-bold">&#10004; 3</span></td><td class='border-r border-white px-2 py-1'><span class="text-red-500 font-bold">&#10008;</span></td><td class='border-r border-white px-2 py-1'><span class="text-green-500 font-bold">&#10004; 2</span></td><td class='border-r border-white px-2 py-1'><span class="text-red-500 font-bold">&#10008;</span></td><td class='border-r border-white px-2 py-1'><span class="text-green-500 font-bold">&#10004; 14</span></td></tr>
<tr data-empresa="SC-BASTARDS BEBIDAS SC LTDA"><td class="border-r border-white px-2 py-1 whitespace-nowrap bg-gray-900 text-gray-100">JUICY JILL</td><td class='border-r border-white px-2 py-1'><span class="text-green-500 font-bold">&#10004; 1</span></td><td class='border-r border-white px-2 py-1'><span class="text-red-500 font-bold">&#10008;</span></td><td class='border-r border-white px-2 py-1'><span class="text-green-500 font-bold">&#10004; 1</span></td><td class='border-r border-white px-2 py-1'><span class="text-red-500 font-bold">&#10008;</span></td><td class='border-r border-white px-2 py-1'><span class="text-green-500 font-bold">&#10004; 3</span></td></tr>
<tr data-empresa="SC-BASTARDS BEBIDAS SC LTDA"><td class="border-r border-white px-2 py-1 whitespace-nowrap bg-gray-900 text-gray-100">MARK THE SHADOW</td><td class='border-r border-white px-2 py-1'><span class="text-green-500 font-bold">&#10004; 1</span></td><td class='border-r border-white px-2 py-1'><span class="text-red-500 font-bold">&#10008;</span></td><td class='border-r border-white px-2 py-1'><span class="text-green-500 font-bold">&#10004; 1</span></td><td class='border-r border-white px-2 py-1'><span class="text-red-500 font-bold">&#10008;</span></td><td class='border-r border-white px-2 py-1'><span class="text-green-500 font-bold">&#10004; 22</span></td></tr>
<tr data-empresa="SC-BASTARDS BEBIDAS SC LTDA"><td class="border-r border-white px-2 py-1 whitespace-nowrap bg-gray-900 text-gray-100">OLD BUT GOLD</td><td class='border-r border-white px-2 py-1'><span class="text-red-500 font-bold">&#10008;</span></td><td class='border-r border-white px-2 py-1'><span class="text-red-500 font-bold">&#10008;</span></td><td class='border-r border-white px-2 py-1'><span class="text-green-500 font-bold">&#10004; 2</span></td><td class='border-r border-white px-2 py-1'><span class="text-red-500 font-bold">&#10008;</span></td><td class='border-r border-white px-2 py-1'><span class="text-red-500 font-bold">&#10008;</span></td></tr>
<tr data-empresa="SC-BASTARDS BEBIDAS SC LTDA"><td class="border-r border-white px-2 py-1 whitespace-nowrap bg-gray-900 text-gray-100">PINA A VIVA</td><td class='border-r border-white px-2 py-1'><span class="text-red-500 font-bold">&#10008;</span></td><td class='border-r border-white px-2 py-1'><span class="text-red-500 font-bold">&#10008;</span></td><td class='border-r border-white px-2 py-1'><span class="text-green-500 font-bold">&#10004; 2</span></td><td class='border-r border-white px-2 py-1'><span class="text-red-500 font-bold">&#10008;</span></td><td class='border-r border-white px-2 py-1'><span class="text-green-500 font-bold">&#10004; 8</span></td></tr>
<tr data-empresa="SC-BASTARDS BEBIDAS SC LTDA"><td class="border-r border-white px-2 py-1 whitespace-nowrap bg-gray-900 text-gray-100">RANNA RIDER</td><td class='border-r border-white px-2 py-1'><span class="text-red-500 font-bold">&#10008;</span></td><td class='border-r border-white px-2 py-1'><span class="text-red-500 font-bold">&#10008;</span></td><td class='border-r border-white px-2 py-1'><span class="text-red-500 font-bold">&#10008;</span></td><td class='border-r border-white px-2 py-1'><span class="text-red-500 font-bold">&#10008;</span></td><td class='border-r border-white px-2 py-1'><span class="text-green-500 font-bold">&#10004; 14</span></td></tr>
<tr data-empresa="SC-BASTARDS BEBIDAS SC LTDA"><td class="border-r border-white px-2 py-1 whitespace-nowrap bg-gray-900 text-gray-100">UM BRINDE A ELAS</td><td class='border-r border-white px-2 py-1'><span class="text-red-500 font-bold">&#10008;</span></td><td class='border-r border-white px-2 py-1'><span class="text-red-500 font-bold">&#10008;</span></td><td class='border-r border-white px-2 py-1'><span class="text-red-500 font-bold">&#10008;</span></td><td class='border-r border-white px-2 py-1'><span class="text-red-500 font-bold">&#10008;</span></td><td class='border-r border-white px-2 py-1'><span class="text-green-500 font-bold">&#10004; 4</span></td></tr>
<tr data-empresa="SC-BASTARDS BEBIDAS SC LTDA"><td class="border-r border-white px-2 py-1 whitespace-nowrap bg-gray-900 text-gray-100">WELT PILSEN</td><td class='border-r border-white px-2 py-1'><span class="text-green-500 font-bold">&#10004; 9</span></td><td class='border-r border-white px-2 py-1'><span class="text-red-500 font-bold">&#10008;</span></td><td class='border-r border-white px-2 py-1'><span class="text-red-500 font-bold">&#10008;</span></td><td class='border-r border-white px-2 py-1'><span class="text-red-500 font-bold">&#10008;</span></td><td class='border-r border-white px-2 py-1'><span class="text-red-500 font-bold">&#10008;</span></td></tr>
<tr data-empresa="SC-BASTARDS BEBIDAS SC LTDA"><td class="border-r border-white px-2 py-1 whitespace-nowrap bg-gray-900 text-gray-100">WELT RED ALE</td><td class='border-r border-white px-2 py-1'><span class="text-red-500 font-bold">&#10008;</span></td><td class='border-r border-white px-2 py-1'><span class="text-red-500 font-bold">&#10008;</span></td><td class='border-r border-white px-2 py-1'><span class="text-green-500 font-bold">&#10004; 1</span></td><td class='border-r border-white px-2 py-1'><span class="text-red-500 font-bold">&#10008;</span></td><td class='border-r border-white px-2 py-1'><span class="text-red-500 font-bold">&#10008;</span></td></tr>
<tr data-empresa="SC-BASTARDS BEBIDAS SC LTDA"><td class="border-r border-white px-2 py-1 whitespace-nowrap bg-gray-900 text-gray-100">WILLIE THE BITTER</td><td class='border-r border-white px-2 py-1'><span class="text-green-500 font-bold">&#10004; 1</span></td><td class='border-r border-white px-2 py-1'><span class="text-red-500 font-bold">&#10008;</span></td><td class='border-r border-white px-2 py-1'><span class="text-green-500 font-bold">&#10004; 2</span></td><td class='border-r border-white px-2 py-1'><span class="text-red-500 font-bold">&#10008;</span></td><td class='border-r border-white px-2 py-1'><span class="text-green-500 font-bold">&#10004; 24</span></td></tr>
<tr data-empresa="SC-BASTARDS BEBIDAS SC LTDA"><td class="border-r border-white px-2 py-1 whitespace-nowrap bg-gray-900 text-gray-100">XP 084 COCONUT BURST</td><td class='border-r border-white px-2 py-1'><span class="text-red-500 font-bold">&#10008;</span></td><td class='border-r border-white px-2 py-1'><span class="text-red-500 font-bold">&#10008;</span></td><td class='border-r border-white px-2 py-1'><span class="text-red-500 font-bold">&#10008;</span></td><td class='border-r border-white px-2 py-1'><span class="text-red-500 font-bold">&#10008;</span></td><td class='border-r border-white px-2 py-1'><span class="text-green-500 font-bold">&#10004; 5</span></td></tr>
<tr data-empresa="SC-BASTARDS BEBIDAS SC LTDA"><td class="border-r border-white px-2 py-1 whitespace-nowrap bg-gray-900 text-gray-100">XP 094 HOP HEADS</td><td class='border-r border-white px-2 py-1'><span class="text-green-500 font-bold">&#10004; 1</span></td><td class='border-r border-white px-2 py-1'><span class="text-red-500 font-bold">&#10008;</span></td><td class='border-r border-white px-2 py-1'><span class="text-red-500 font-bold">&#10008;</span></td><td class='border-r border-white px-2 py-1'><span class="text-red-500 font-bold">&#10008;</span></td><td class='border-r border-white px-2 py-1'><span class="text-red-500 font-bold">&#10008;</span></td></tr>
<tr data-empresa="SC-BASTARDS BEBIDAS SC LTDA"><td class="border-r border-white px-2 py-1 whitespace-nowrap bg-gray-900 text-gray-100">XP 095 BROWN IPA</td><td class='border-r border-white px-2 py-1'><span class="text-red-500 font-bold">&#10008;</span></td><td class='border-r border-white px-2 py-1'><span class="text-red-500 font-bold">&#10008;</span></td><td class='border-r border-white px-2 py-1'><span class="text-green-500 font-bold">&#10004; 2</span></td><td class='border-r border-white px-2 py-1'><span class="text-red-500 font-bold">&#10008;</span></td><td class='border-r border-white px-2 py-1'><span class="text-red-500 font-bold">&#10008;</span></td></tr>
<tr data-empresa="SC-BASTARDS BEBIDAS SC LTDA"><td class="border-r border-white px-2 py-1 whitespace-nowrap bg-gray-900 text-gray-100">XP GOLDEN FLAMINGO</td><td class='border-r border-white px-2 py-1'><span class="text-red-500 font-bold">&#10008;</span></td><td class='border-r border-white px-2 py-1'><span class="text-red-500 font-bold">&#10008;</span></td><td class='border-r border-white px-2 py-1'><span class="text-red-500 font-bold">&#10008;</span></td><td class='border-r border-white px-2 py-1'><span class="text-red-500 font-bold">&#10008;</span></td><td class='border-r border-white px-2 py-1'><span class="text-green-500 font-bold">&#10004; 33</span></td></tr>
<tr data-empresa="SC-BASTARDS BEBIDAS SC LTDA"><td class="border-r border-white px-2 py-1 whitespace-nowrap bg-gray-900 text-gray-100">ZE DO MORRO</td><td class='border-r border-white px-2 py-1'><span class="text-red-500 font-bold">&#10008;</span></td><td class='border-r border-white px-2 py-1'><span class="text-red-500 font-bold">&#10008;</span></td><td class='border-r border-white px-2 py-1'><span class="text-red-500 font-bold">&#10008;</span></td><td class='border-r border-white px-2 py-1'><span class="text-red-500 font-bold">&#10008;</span></td><td class='border-r border-white px-2 py-1'><span class="text-green-500 font-bold">&#10004; 19</span></td></tr>
</tbody>
      </table>
    </div>

  </main>

  <script>
    document.addEventListener('DOMContentLoaded', () => {
      const radios = document.querySelectorAll('input[name="empresa-filter"]');
      const rows = document.querySelectorAll('tbody tr');
      const btn  = document.getElementById('btn-filter');

      radios.forEach(radio => {
        radio.addEventListener('change', () => {
          btn.textContent = radio.value;
          rows.forEach(tr => {
            tr.style.display = tr.dataset.empresa === radio.value ? '' : 'none';
          });
        });
      });

      // dispara evento inicial para aplicar filtro default
      const inicial = Array.from(radios).find(r => r.checked);
      if (inicial) inicial.dispatchEvent(new Event('change'));
    });
  </script>
</body>
</html>